### PR TITLE
Added validation for signatures and distance matrix. Updated tests

### PR DESCRIPTION
**Pull request by skillachie**
https://github.com/wmayner/pyemd/issues/8

### CODE REVIEW

**Comment by skillachie** [comment]
I am not sure what happens on Travis during the build process. This is my first Cython related based commit so i might have missed something. 

It currently builds locally

`========================================================================== test session starts ==========================================================================
platform linux -- Python 3.4.3, pytest-2.9.0, py-1.4.31, pluggy-0.3.1
rootdir: /home/skillachie/pyemd, inifile: pytest.ini
collected 10 items 

README.rst .
pyemd/__init__.py .
test/test_pyemd.py ........

======================================================================= 10 passed in 0.13 seconds =======================================================================
`

**Comment by wmayner** [comment]
Thanks for the PR!

I don't think that the variable-length signatures will work, which probably explains why the build is failing. The comments in the C++ implementation suggest that the signatures are assumed to be the same size. When I use signatures of different lengths, I get garbage results and occasionally a `malloc`-related segfault, confirming this.

There is some code in `pyemd/lib/emd_hat_signatures_interface.hpp` that looks like it may accept variable-length signatures, but that's not the part that's being exposed, since it's a more complicated interface that has both features and weights. This library aims to provide just the Earth Mover's Distance between arrays of floats, without any notion of features or weights.

So, there should probably be a check that ensures the signatures are the same size.

Also, I'd like to keep the Python style consistent throughout the repo—in general, this means conforming to PEP8 (4-space indentation, spaces after commas, etc.). Most editors support PEP8 linting for Python, but if yours doesn't then you can install the linter directly with `pip install pep8` and run it directly on the source.

**Comment by skillachie** [comment]
No problem. Just my small way of helping. 

That explains it. I had assumed signatures could be different sizes. I will make the changes and PEPify the code

**Comment by skillachie** [comment]
-Added the checks for  the signatures
-Updated tests
-Pepify

**Pull request merged**
