### PR TITLE
Getting the flows

### PR DESCRIPTION
**Pull request by rlouf**
The flows now work on my machine after updating the code from the repository (I was working on an old version previously).

### CODE REVIEW

**Comment by rlouf** [comment]
Tested with Python 2.7 but doesn't build with Python 3, I have no idea why.

**Comment by wmayner** [comment]
I fixed a couple of problems and now things compile properly and the tests pass.

Couple of things:
- Thanks for adding some tests. However, there aren't any that actually check that the flows are correct—they just check that the new function raises the appropriate errors.
- It seems like `emd_hat_gd_metric_double_wrapper_vector` isn't actually used (only `emd_hat_gd_metric_double_wrapper` is used). Can we just delete it?

**Comment by wmayner** [comment]
Oh, and I forgot to mention that the README should be updated as well.

**Comment by rlouf** [comment]
Great, thank you!

- I would add them if I knew how to edit a pull request (taking your changes into account)
- Indeed, I was waiting to see whether we prefered having a function that outputs both emd and flows, or only flows.
- I'll update the README once the two points above are marked as solved :)

**Comment by wmayner** [comment]
- Pull requests are just a GitHub concept to make collaboration more decentralized—underneath, everything is just a Git repository. When I added commits to this PR, I was just committing to the `master` branch of your [fork](https://github.com/rlouf/pyemd). So, you just need to run `git pull` to incorporate my changes, .
- I think we should go with returning the EMD value and the flows, since the user can always discard the former if it's not needed (e.g. `_, flows = emd_with_flows(...)`).
- The latest commit makes things compatible with older versions of `gcc` that implement older C++ standards, which don't include the `auto` keyword.

**Comment by rlouf** [comment]
Ok, got it, I'm on it. Thanks for the changes!

**Comment by rlouf** [comment]
The README was already changed. I need to add some test, though. I checked with situation where the mass is conserved and it works, I am not sure what I should obtain if the mass is not conserved. I may need to dive deeper in the code...

**Comment by wmayner** [comment]
Oh yeah, I only looked at the "Usage" section—thanks. It may be worth adding a similar example for the new function in that section too, even though it's a bit redundant, just so people don't miss it.

It should be fine to get the flows by hand in some easy edge cases, and then maybe one more complicated case. These tests are mostly functioning as checks against regression bugs.

**Comment by rlouf** [comment]
I just added some tests. I reproduced the existing ones, and added two new ones. Good to go for me.

**Comment by rlouf** [comment]
I fixed the readme and added a caveat: the flows to/from extra mass bin are not shown in the flow matrix.

**Comment by wmayner** [comment]
I changed things a bit so that `emd` doesn't use flows—this avoids an unnecessary call to [`transform_flow_to_regular`](https://github.com/wmayner/pyemd/blob/develop/pyemd/lib/emd_hat_impl.hpp#L322).

I think this is ready to merge! Thank you for your work on this 😄

**Comment by rlouf** [comment]
Thank you for helping with my messy code! I hope this will be helpful for some people---at least for me :)

**Pull request merged**
